import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>EVENTS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link href="/" passHref>
            <a>Home</a>
          </Link>
          <Link href="/events" passHref>
            <a>Events</a>
          </Link>
          <Link href="/about-us" passHref>
            <a>About Us</a>
          </Link>
        </nav>
      </header>
      <main className='main-content'>
        {data.map(evt => {
          return (
            <Link key={evt.id} href={`/events/${evt.id}`} passHref>
              <a>
                <Image alt={evt.title} src={evt.image} width={300} height={150} />
                <h2>{evt.title}</h2>
                <p>{evt.description}</p>
              </a>
            </Link>
          )
        })}
      </main>
    </div>
  )
}


export async function getServerSideProps() {

  const { events_categories } = await import('/data/data.json')
  // const res = await fetch('/data/data.json')
  // const data = await res.json()

  return {
    props: {
      data: events_categories
    }
  }
}
