import Head from 'next/head'
import Image from 'next/image'

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>EVENTS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className='main-content'>
        {data.map(evt => {
          return (
            <a key={evt.id} href={`/events/${evt.id}`}>
              <Image alt={evt.title} src={evt.image} width={300} height={150} />
              <h2>{evt.title}</h2>
              <p>{evt.description}</p>
            </a>
          )
        })}
      </main>
    </div>
  )
}


export async function getServerSideProps() {

  const { events_categories } = await import('/data/data.json')
  // const res = await fetch('/data/data.json')
  // const data = await res.json()

  return {
    props: {
      data: events_categories
    }
  }
}
